var tipuesearch = {"pages": [
{"title":"404 - file not found","tags":" ","url":"/404.html","text":"Ex-Pat Pup provides resources and information to move your pet from the US to the UK on your own with ease."},
{"title":"About","tags":" ","url":"/about/","text":"All the information you need to move your pet from the US to the UK"},
{"title":"Third-Country Certificate","tags":" ","url":"/annex/","text":"The Annex is the third-country official veterinary certificate for the United States.  This article provides both the Annex IV for download as well as more information on the paperwork"},
{"title":"TEST","tags":" ","url":"/421071d5.html","text":""},
{"title":"Can my pet travel?","tags":" ","url":"/pet-travel-restrictions","text":"Information on banned breeds, airline restrictions and other reasons your pet may not easily move to the UK"},
{"title":"Crates","tags":" ","url":"/crates","text":""},
{"title":null,"tags":" ","url":"/feed.xml","text":""},
{"title":"Final vet visit and paperwork","tags":" ","url":"/final_vet_visit_and_paperwork","text":""},
{"title":"Fit to Fly Declaration","tags":" ","url":"/fit-to-fly-declaration/","text":"Most airlines require your pet be examined by a vet and deemed fit to fly.  You can find the document provided by the USDA on this page, as well as details on what information is necessary"},
{"title":"Moving your pet from the US to the UK","tags":" ","url":"/","text":"Ex-Pat Pup provides resources and information to move your pet from the US to the UK on your own with ease"},
{"title":"FAQs","tags":" ","url":"/FAQs/","text":"Does my pet need a rabies vaccination?  Can my pet travel?  What is a pet password and where can I get one?  These questions and more answered here!"},
{"title":"Resources","tags":" ","url":"/resources/","text":"Information and resources regarding all paperwork needed for your pet’s travel.  Download documents here to bring to your vet, including the Annex IV and a handy paperwork checklist"},
{"title":"Guides","tags":" ","url":"/guides/","text":"All the information you need to move your pet from the US to the UK"},
{"title":"Products","tags":" ","url":"/products/","text":""},
{"title":null,"tags":" ","url":"/css/main.css","text":""},
{"title":"Microchipping and Rabies Vaccination","tags":" ","url":"/microchipping_and_rabies_vaccination","text":""},
{"title":"Paperwork Checklist","tags":" ","url":"/paperwork-checklist/","text":"Download this checklist to keep track of all documents needed for your pet to travel"},
{"title":"What is a pet passport?","tags":" ","url":"/pet-passport","text":"Pet passports are commonly mentioned on pet travel websites.  This article explains what a pet passport is and where you can find one"},
{"title":"Purchase your pet’s crate","tags":" ","url":"/purchase_your_pets_crate","text":""},
{"title":"Plan Your Flight","tags":" ","url":"/plan_your_flight","text":""},
{"title":"Make plans for your pet’s final vet visit and USDA endorsement","tags":" ","url":"/final_vet_visit_and_usda","text":""},
{"title":"Privacy","tags":" ","url":"/privacy/","text":"ExPatPup's privacy policy"},
{"title":"Rabies Certificate","tags":" ","url":"/rabies-certificate/","text":"Your pet will need a certificate showing that they have had their rabies vaccination.  Here’s an example of what a rabies certificate looks like"},
{"title":"Vaccine Information","tags":" ","url":"/rabies-vaccination-information","text":"The UK has strict rules regarding when the rabies vaccination takes place.  Knowing if a rabies vaccination is needed is crucial to planning your pet’s journey."},
{"title":"Search","tags":" ","url":"/search/","text":""},
{"title":"Steel Fittings","tags":" ","url":"/steel-fittings","text":""},
{"title":"Step-by-Step Guide","tags":" ","url":"/step-by-step-walkthrough","text":"This Step-by-Step guide will walk you through how to move your pet from the US to the UK without any quarantine"},
{"title":"Stickers","tags":" ","url":"/stickers","text":""},
{"title":"Buying a Crate","tags":" ","url":"/buying-a-crate","text":"Both the UK and airlines have requirements concerning your pet's travel container.  Consult this guide to help you with your purchase."},
{"title":"USDA endorsement","tags":" ","url":"/usda_endorsement","text":""},
{"title":"USDA information","tags":" ","url":"/usda/","text":"After you have obtained all paperwork necessary for travel it will need to be endorsed by the USDA.  This article provides information on USDA offices including hours and locations"},
{"title":"Waterbowls","tags":" ","url":"/waterbowls","text":""},
{"title":"What do I need to move my pet?","tags":" ","url":"/what-you-need","text":"Airline approved crates, clearance fees, paperwork… know everything you’ll need to move your pet overseas"},
{"title":"What you will need","tags":" ","url":"/what_you_will_need","text":""}
]};
