# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ex-Pat Pup
email: contact@expatpup.com
description: > # this means to ignore newlines until "baseurl:"
  Ex-Pat Pup provides resources and information to move your pet
  from the US to the UK on your own with ease.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://expatpup.com" # the base hostname & protocol for your site
# twitter_username: expatpup
# github_username:  jgroto

# Build settings
markdown: kramdown
